### ISSUE TITLE
Funkiness with CHECKPOINT_NAME

### ISSUE THREAD

**Issue by mwalker412** [amitesh863/nbeats_forecast#1]
When training a new model, "_checkpoint_file_name_" kwarg needs to be set (or model.CHECKPOINT_NAME set directly). Leaving it at default value can produce host of size mismatch errors that don't give information as to what's going on. Suggest raising error in that case instead of allowing "RuntimeError" via torch.

**Comment by amitesh863** [comment]
Hey.
The funkiness comes in when training stops abruptly.
If the training has stopped in between, you can delete the temporary files and it will work properly.
