### ISSUE TITLE
Where is the NBeatsNet ?

### ISSUE THREAD

**Issue by houchenyu** [amitesh863/nbeats_forecast#2]
As declared in nbeats_forecast.py , `from nbeats_pytorch.model import NBeatsNet`

But I can't find the `model.py` to see the code of NBeatsNet.

**Comment by amitesh863** [comment]
The base model can be found here:
https://github.com/philipperemy/n-beats.
The repository was created to provide a simple scikit-learn type functionality to the existing model.
My code uses nbeats-pytorch 1.3.0 as base:
https://pypi.org/project/nbeats-pytorch/1.3.0/
