### ISSUE TITLE
data_generator() method is wrong

### ISSUE THREAD

**Issue by houchenyu** [amitesh863/nbeats_forecast#4]
In `data_generator`, you define a split() method to split data into multiple batches, but the while condition ` len(arr) > size`  is incorrect because arr = (x_full, y_full) which means len(arr) is equal to 2 forever. I found this bug when I debug into your code. Besides, I can't find the definition of the model, could you please show me your complete code in github.

**Comment by amitesh863** [comment]
Hi,
The method works as intended for batch size check. The base code can be found here:
https://github.com/philipperemy/n-beats.
The repository was created to provide a simple scikit-learn type functionality to the existing model.
My code uses nbeats-pytorch 1.3.0 as base:
https://pypi.org/project/nbeats-pytorch/1.3.0/
