### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'thetas_dims'

### ISSUE THREAD

**Issue by ghost** [amitesh863/nbeats_forecast#5]
`model = NBeats(data=data, period_to_forecast=194, train_percent=0.75)`

This code used to work but now it won't. Is this beacause of using wrong version of packages?

**Comment by amitesh863** [comment]
Hi, are you using the 1.3.6 version? Please update nbeats-forecast to 1.3.7.

**Comment by ludomare** [comment]
Hi, I have the same problem now with the 1.3.7

**Comment by amitesh863** [comment]
> Hi, I have the same problem now with the 1.3.7

Can you check the version of nbeats-pytorch?( It should be 1.3.0). If you have manually upgraded the nbeats-pytorch package, then please downgrade it to 1.3.0
